cmake: expand library dependencies with USE_CMAKE_FIND_PACKAGE_LLVM
When we use -DUSE_CMAKE_FIND_PACKAGE_LLVM=ON, we do not expand
dependecies and build fails with linker errors like:
/usr/bin/ld: lib/libkleeModule.a(ModuleUtil.cpp.o): undefined reference to symbol '_ZNK4llvm6object7Archive5Child7getNameEv'
/usr/lib64/../lib64/libLLVMObject.so.4: error adding symbols: DSO missing from command line
clang-4.0.0: error: linker command failed with exit code 1 (use -v to see invocation)

So let LLVM compute also the transitive close as it used to do so in
LLVM < 3.5.

Signed-off-by: Jiri Slaby <jirislaby@gmail.com>